// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHXDUgqNfm4_94dKPmSWOl1qCvPwJiiDE',
    appId: '1:672445411355:web:0f9fe2aa4640814d3588be',
    messagingSenderId: '672445411355',
    projectId: 'flutter-chattapp',
    authDomain: 'flutter-chattapp.firebaseapp.com',
    databaseURL: 'https://flutter-chattapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-chattapp.appspot.com',
    measurementId: 'G-CZYSL9XP6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK0ovVO0vvuwS8ds9Wo0GVKptdjYkqUz0',
    appId: '1:672445411355:android:d1516c1929e07c5d3588be',
    messagingSenderId: '672445411355',
    projectId: 'flutter-chattapp',
    databaseURL: 'https://flutter-chattapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-chattapp.appspot.com',
  );
}
